/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    java
    `java-library`
    id("io.spring.dependency-management") version "1.1.5" apply false
    id("org.springframework.boot") version "3.5.3" apply false
}

allprojects {
    group = "com.reyga-dev.starter"
    version = "1.0.0"

    repositories {
        // Use Maven Central for resolving dependencies.
        mavenCentral()
    }
}


subprojects {
    apply(plugin = "java-library")
    apply(plugin = "io.spring.dependency-management")

    dependencies {
        // Use JUnit test framework.
        testImplementation("junit:junit:4.13")

        // This dependency is exported to consumers, that is to say found on their compile classpath.
        api("org.apache.commons:commons-math3:3.6.1")

        // This dependency is used internally, and not exposed to consumers on their own compile classpath.
        implementation("com.google.guava:guava:29.0-jre")

        /**
            Base Dependencies for all module
         */
        api("jakarta.persistence:jakarta.persistence-api:3.1.0")
        implementation("org.springframework.boot:spring-boot-starter:3.5.3")
        implementation("org.springframework.boot:spring-boot-autoconfigure:3.5.3")
        implementation("org.springframework.boot:spring-boot-starter-web:3.5.3")
        compileOnly("org.projectlombok:lombok:1.18.30")
        annotationProcessor("org.projectlombok:lombok:1.18.30")

    }
}

