import java.io.File

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.1/userguide/building_java_projects.html
 */

val projectGroup: String by project
val projectVersion: String by project
val javaVersion = providers.gradleProperty("javaVersion").get().toInt()
val springBootVersion: String by project
val junitJupiterVersion: String by project
val mockitoVersion: String by project
val commonsMathVersion: String by project
val guavaVersion: String by project
val jakartaPersistenceApiVersion: String by project
val lombokVersion: String by project

plugins {
    // Apply the java-library plugin for API and implementation separation.
    java
    `java-library`
    id("io.spring.dependency-management") apply false
    id("org.springframework.boot") apply false
}

allprojects {
    group = projectGroup
    version = projectVersion

    repositories {
        // Use Maven Central for resolving dependencies.
        mavenCentral()
    }
}


subprojects {
    apply(plugin = "java-library")
    apply(plugin = "io.spring.dependency-management")

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(javaVersion))
        }
    }

    dependencies {
        // Use JUnit 5 + Mockito for tests.
        testImplementation("org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion")
        testImplementation("org.junit.jupiter:junit-jupiter-params:$junitJupiterVersion")
        testImplementation("org.mockito:mockito-core:$mockitoVersion")
        testImplementation("org.mockito:mockito-junit-jupiter:$mockitoVersion")
        testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion")

        // This dependency is exported to consumers, that is to say found on their compile classpath.
        api("org.apache.commons:commons-math3:$commonsMathVersion")

        // This dependency is used internally, and not exposed to consumers on their own compile classpath.
        implementation("com.google.guava:guava:$guavaVersion")

        /**
            Base Dependencies for all module
         */
        api("jakarta.persistence:jakarta.persistence-api:$jakartaPersistenceApiVersion")
        implementation("org.springframework.boot:spring-boot-starter:$springBootVersion")
        implementation("org.springframework.boot:spring-boot-autoconfigure:$springBootVersion")
        implementation("org.springframework.boot:spring-boot-starter-web:$springBootVersion")
        compileOnly("org.projectlombok:lombok:$lombokVersion")
        annotationProcessor("org.projectlombok:lombok:$lombokVersion")

    }

    tasks.test {
        useJUnitPlatform()
    }
}
