import org.gradle.api.publish.PublishingExtension
import org.gradle.api.publish.maven.tasks.PublishToMavenRepository

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.1/userguide/building_java_projects.html
 */

val projectGroup: String by project
val projectVersion: String by project
val javaVersion = providers.gradleProperty("javaVersion").get().toInt()
val springBootVersion: String by project
val junitJupiterVersion: String by project
val mockitoVersion: String by project
val byteBuddyVersion: String by project
val lombokVersion: String by project

plugins {
    // Apply the java-library plugin for API and implementation separation.
    java
    `java-library`
    id("io.spring.dependency-management") apply false
    id("org.springframework.boot") apply false
}

allprojects {
    group = projectGroup
    version = projectVersion

    repositories {
        // Use Maven Central for resolving dependencies.
        mavenCentral()
    }
}


subprojects {
    apply(plugin = "maven-publish")

    if (name != "foundation-bom") {
        apply(plugin = "java-library")
        apply(plugin = "io.spring.dependency-management")
    }

    val nexusReleaseRepositoryUrl = providers.gradleProperty("nexusReleaseRepositoryUrl")
    val nexusSnapshotRepositoryUrl = providers.gradleProperty("nexusSnapshotRepositoryUrl")
    val nexusUsername = providers.gradleProperty("nexusUsername")
    val nexusPassword = providers.gradleProperty("nexusPassword")
    val nexusAllowInsecureProtocol = providers.gradleProperty("nexusAllowInsecureProtocol")
            .map(String::toBoolean)
            .getOrElse(false)

    extensions.configure<PublishingExtension> {
        repositories {
            maven {
                name = "nexus"
                url = uri(
                        if (project.version.toString().endsWith("-SNAPSHOT")) {
                            nexusSnapshotRepositoryUrl.get()
                        } else {
                            nexusReleaseRepositoryUrl.get()
                        }
                )
                isAllowInsecureProtocol = nexusAllowInsecureProtocol
                credentials {
                    username = nexusUsername.orNull
                    password = nexusPassword.orNull
                }
            }
        }
    }

    tasks.withType<PublishToMavenRepository>().configureEach {
        doFirst {
            require(nexusUsername.orNull?.isNotBlank() == true) {
                "Nexus username is not configured. Set nexusUsername in gradle.properties."
            }
            require(nexusPassword.orNull?.isNotBlank() == true) {
                "Nexus password is not configured. Set nexusPassword in gradle.properties."
            }
        }
    }

    if (name != "foundation-bom") {
        java {
            toolchain {
                languageVersion.set(JavaLanguageVersion.of(javaVersion))
            }
        }

        dependencies {
            // Use JUnit 5 + Mockito for tests.
            testImplementation("org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion")
            testImplementation("org.junit.jupiter:junit-jupiter-params:$junitJupiterVersion")
            testImplementation("org.mockito:mockito-core:$mockitoVersion")
            testImplementation("org.mockito:mockito-junit-jupiter:$mockitoVersion")
            testImplementation("net.bytebuddy:byte-buddy:$byteBuddyVersion")
            testRuntimeOnly("net.bytebuddy:byte-buddy-agent:$byteBuddyVersion")
            testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion")
            testRuntimeOnly("org.junit.platform:junit-platform-launcher")

            compileOnly("org.projectlombok:lombok:$lombokVersion")
            annotationProcessor("org.projectlombok:lombok:$lombokVersion")

        }

        tasks.test {
            useJUnitPlatform()
        }
    }
}
