# Set to JAVA JDK Path directory
#org.gradle.java.home={JDK PATH}

projectGroup=com.reyga-dev.starter
projectVersion=1.0.0

javaVersion=25

springDependencyManagementPluginVersion=1.1.5
springBootPluginVersion=4.0.0
springBootVersion=4.0.0

junitJupiterVersion=5.12.2
mockitoVersion=5.14.2
commonsMathVersion=3.6.1
guavaVersion=29.0-jre
jakartaPersistenceApiVersion=3.1.0
lombokVersion=1.18.38
mapstructVersion=1.6.3
lombokMapstructBindingVersion=0.2.0
ojdbcVersion=23.7.0.25.01
springJdbcVersion=6.2.9
jakartaValidationApiVersion=3.1.1
resilience4jVersion=2.3.0
caffeineVersion=3.1.8
logbackClassicVersion=1.5.18
janinoVersion=3.1.12
